from dataclasses import dataclass
from pathlib import Path

from greenfleet.artifacts.base_artifact import BaseArtifact


@dataclass
class DataIngestionArtifact(BaseArtifact):
    """
    Artifact generated by the data ingestion stage.
    """

    source_data_path: Path
    ingested_data_path: Path
    metadata_file_path: Path

    row_count: int
    column_count: int
    column_names: list[str]