from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class DataTransformationArtifact:
    """
    Stores the output paths and metadata generated by
    the data transformation component.
    """

    transformed_train_file_path: Path

    transformed_test_file_path: Path

    preprocessor_file_path: Path

    feature_names_file_path: Path

    transformation_report_file_path: Path

    train_shape: Optional[tuple] = None

    test_shape: Optional[tuple] = None

    numerical_feature_count: int = 0

    categorical_feature_count: int = 0

    total_transformed_feature_count: int = 0

    is_transformation_successful: bool = False

    def __repr__(self) -> str:
        return (
            "DataTransformationArtifact("
            f"transformed_train_file_path="
            f"'{self.transformed_train_file_path}', "
            f"transformed_test_file_path="
            f"'{self.transformed_test_file_path}', "
            f"preprocessor_file_path="
            f"'{self.preprocessor_file_path}', "
            f"feature_names_file_path="
            f"'{self.feature_names_file_path}', "
            f"transformation_report_file_path="
            f"'{self.transformation_report_file_path}', "
            f"train_shape={self.train_shape}, "
            f"test_shape={self.test_shape}, "
            f"numerical_feature_count="
            f"{self.numerical_feature_count}, "
            f"categorical_feature_count="
            f"{self.categorical_feature_count}, "
            f"total_transformed_feature_count="
            f"{self.total_transformed_feature_count}, "
            f"is_transformation_successful="
            f"{self.is_transformation_successful}"
            ")"
        )